export type StackParamList = {
  Landing: undefined;
  Main: undefined;
  Details1: undefined;
  StoryReadCategory: undefined;
  ComponentTest: undefined;
  SignUpName: undefined;
  StoryWriteSelect: undefined;
  StoryWriteCreate: undefined;
  Mypage: undefined;
  AuthSelectionScreen: undefined;
  Login: undefined;
  SignUp: undefined;
  StoryReadDetail: undefined;
  StoryRoomSelectScreen: undefined;
};
export type RootStackParamList = {
  Splash: undefined;
  Main: undefined;
  ComponentTest: undefined;
  StoryReadCategory: undefined;
  SignUpName: undefined;
  SignUpEmail: undefined;
  StoryWriteSelect: undefined;
  StoryWriteCreate: undefined;
  Mypage: undefined;
  AuthSelectionScreen: undefined;
  Login: undefined;
  SignUp: undefined;
  StoryReadDetail: undefined;
  StoryRoomSelectScreen: undefined;
};
